name: Deploy Preview Version
on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TNUCHAPORN_TRUCKMANAGER }}"
          projectId: tnuchaporn-truckmanager
          expires: 15d
          channelId: https://tnuchaporn-truckmanager-demo.web.app
